---
title: "Chapter One"
---


Citations and references work either in lists[@Atzeni;@fouquet2006seven;@langmuir1928oscillations] or just on their own.[@MetropolisHastings]

We can also set up some Python imports; the code just below will not appear in the final output document.


```{python}
import matplotlib.pyplot as plt
import matplotlib_inline.backend_inline
import pandas as pd
import os

matplotlib_inline.backend_inline.set_matplotlib_formats("svg")
```

And then we can also make a chart:

```{python}
#| label: fig-example-figure
#| fig-cap: "Some wiggly lines generated by code in the same file as the text"
import numpy as np
from numpy.random import default_rng

# Fixing random state for reproducibility
rng = default_rng()

dt = 0.01
t = np.arange(0, 30, dt)
nse1 = rng.standard_normal(len(t))                 # white noise 1
nse2 = rng.standard_normal(len(t))                 # white noise 2

# Two signals with a coherent part at 10 Hz and a random part
s1 = np.sin(2 * np.pi * 10 * t) + nse1
s2 = np.sin(2 * np.pi * 10 * t) + nse2

fig, axs = plt.subplots(2, 1, figsize=(8, 4))
axs[0].plot(t, s1, t, s2)
axs[0].set_xlim(0, 2)
axs[0].set_xlabel('Time')
axs[0].set_ylabel('s1 and s2')
axs[0].grid(True)

cxy, f = axs[1].cohere(s1, s2, 256, 1. / dt)
axs[1].set_ylabel('Coherence')

fig.tight_layout()
plt.show()
```

And it's also possible to refer to the chart in the text; for example, this one is @fig-example-figure, and it will be reachable via a hyperlink.

Nec feugiat in fermentum posuere urna nec tincidunt. Pellentesque elit eget gravida cum sociis natoque penatibus et magnis. Lorem sed risus ultricies tristique nulla aliquet enim tortor at. Tellus in hac habitasse platea. Urna id volutpat lacus laoreet non curabitur gravida arcu ac. Praesent semper feugiat nibh sed pulvinar. Ullamcorper malesuada proin libero nunc consequat. Id venenatis a condimentum vitae sapien pellentesque habitant morbi. In nisl nisi scelerisque eu ultrices. Etiam sit amet nisl purus.

Sit amet luctus venenatis lectus magna. Enim nec dui nunc mattis enim. Mi bibendum neque egestas congue quisque. Bibendum ut tristique et egestas quis ipsum suspendisse. Augue interdum velit euismod in. Ante metus dictum at tempor commodo ullamcorper a lacus vestibulum. Blandit libero volutpat sed cras ornare arcu. Volutpat blandit aliquam etiam erat velit scelerisque in dictum non. Lectus mauris ultrices eros in cursus turpis massa tincidunt dui. Dignissim cras tincidunt lobortis feugiat. Quam pellentesque nec nam aliquam sem. Est velit egestas dui id. Imperdiet massa tincidunt nunc pulvinar sapien et. Quis risus sed vulputate odio ut enim blandit volutpat. Ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. Cursus turpis massa tincidunt dui ut ornare lectus sit. Sagittis purus sit amet volutpat. Elementum sagittis vitae et leo duis. Nulla aliquet enim tortor at auctor urna nunc id. Nisl purus in mollis nunc sed id semper risus.
